import type { FC, PropsWithChildren } from 'react';

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
};

const AboutLayout: FC<PropsWithChildren> = ({ children }) => {
  return children;
};

export default AboutLayout;
