export const GET_PRODUCTS_REQUEST = 'PRODUCTS/GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'PRODUCTS/GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'PRODUCTS/GET_PRODUCTS_FAILURE';
