# Playwright Testing and GitHub Actions Tutorial: Run Your Playwright Tests on Every Code Commit
# https://www.youtube.com/watch?v=yU2wtTsPF2A

# Secrets and Environment Variables in your GitHub Action
# https://www.youtube.com/watch?v=dPLPSaFqJmY

# TODO:
# Building a Complex Playwright Pipeline in GitHub Actions: Select Environment, Dynamic Shards, and Flexible Execution
# https://medium.com/@vrknetha/building-a-complex-playwright-pipeline-in-github-actions-select-environment-dynamic-shards-and-6a1448427545

name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-unit:
    uses: ./.github/workflows/resuable-tests-steps.yml
    with:
      test-type: 'unit'

  # test-e2e:
  #   uses: ./.github/workflows/resuable-tests-steps.yml
  #   with:
  #     test-type: 'e2e'
